### ISSUE TITLE
TLS grade having hard time to update

### ISSUE THREAD

**Issue by Zaczero** [searx/searx-stats2#50]
I have recently started to host my searx instance and after doing some custom bot filtering I scored poorly on both TLS/CSP grades. It has been fixed by simply whitelisting some ips/user-agents. However days passed and TLS grade is not getting updated whereas CSP refreshed within ~1 day.

What leads me to believe that this is an issue:
* By checking the source I can see that you are requesting https://cryptcheck.fr/https/searx.monicz.pl.json file on which my instance does have an A+ grade.
* By checking other instances' TLS reports I can see that in some cases last scan date is a month old (for example: https://cryptcheck.fr/https/eulie.de last scanned at Mon, 10 Aug).

---

My instance:
https://searx.monicz.pl/

**Comment by dalf** [comment]
Some notes:
* searx-stats2 doesn't use the web site https://cryptcheck.fr (the waiting time can be very long)
* searx-stats2 use the engine of https://cryptcheck.fr : https://github.com/aeris/cryptcheck with a small wrapper https://github.com/dalf/cryptcheck-backend
* the engine is supposed to provide the same results than the website.

I've looked about https://searx.monicz.pl/ : 
* the value has been updated with a grade E today.
* the result says that [HSTS](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) is not supported according to the engine running  (but it is supported according to cryptcheck.fr or at least no issue is shown about that).

The HSTS status is checked this way:
* ```HEAD``` request on ```/```
* check if the ```strict-transport-security``` HTTP header.

For reference:
* the code about that: https://github.com/aeris/cryptcheck/blob/8ec602917d2edcc5fd7a73231e5b438e7d87008e/lib/cryptcheck/tls/https/server.rb
* this comment: https://github.com/aeris/cryptcheck/issues/50#issuecomment-611515318

```
$ curl --head -v https://searx.monicz.pl/
...
< HTTP/2 403 
HTTP/2 403 
< date: Sat, 05 Sep 2020 07:16:33 GMT
date: Sat, 05 Sep 2020 07:16:33 GMT
< alt-svc: quic=":443"; ma=2592000; v="43,46", h3-Q043=":443"; ma=2592000, h3-Q046=":443"; ma=2592000, h3-Q050=":443"; ma=2592000, h3-25=":443"; ma=2592000, h3-27=":443"; ma=2592000
alt-svc: quic=":443"; ma=2592000; v="43,46", h3-Q043=":443"; ma=2592000, h3-Q046=":443"; ma=2592000, h3-Q050=":443"; ma=2592000, h3-25=":443"; ma=2592000, h3-27=":443"; ma=2592000

< 
```

The HSTS fails because the web server returns a HTTP 403 error without the ```strict-transport-security``` header.

So, in the end:
* I don't know why cryptcheck.fr shows an A+ grade (it should be E according to the aeris's comment)
* You can fix the it will fix the ```E``` grade on searx.space this way:
   * Allow the ```HEAD``` method on ```/``` 
   * Make sure to return the ```strict-transport-security``` HTTP header.

**Comment by Zaczero** [comment]
This would explain why there is such a difference.

> I don't know why cryptcheck.fr shows an A+ grade (it should be E according to the aeris's comment)

It's because of my *anti-bot* solution you are getting 403 (forbidden). I have manually whitelisted their IP+User-Agent so it does not require them to meet my requirements. I had to do the same for observatory.mozilla.org so now I am getting A+ there as well.

Could you please use some non-curl User-Agent and/or publicly list IP addresses which you are using so I can whitelist your requests. Whitelisting curl User-Agent itself is not a good idea.

> Allow the HEAD method on /

Head method is allowed. It's all about making use of HTTP/2 + TLS/1.3.

So in the end (do one of the two):
* Send me User-Agent which should be whitelisted
* Send me IP addresses which should be whitelisted

**Comment by unixfox** [comment]
> Could you please use some non-curl User-Agent and/or publicly list IP addresses which you are using so I can whitelist your requests. Whitelisting curl User-Agent itself is not a good idea.

For your whitelist just use the IP from this domain: check.searx.space.

**Comment by dalf** [comment]
>  I had to do the same for observatory.mozilla.org so now I am getting A+ there as well.

Note once https://github.com/searx/searx-stats2/pull/47 is merged, the CSP grade test will run on check.searx.space 
So all tests will come from check.searx.space (not from cryptcheck.fr, not from observatory.mozilla.org).

**Comment by Zaczero** [comment]
> > Could you please use some non-curl User-Agent and/or publicly list IP addresses which you are using so I can whitelist your requests. Whitelisting curl User-Agent itself is not a good idea.
> 
> For your whitelist just use the IP from this domain: `check.searx.space`.
> 
> It's the same domain as filtron rules from searx-docker: https://github.com/searx/searx-docker/blob/master/rules.json#L4
> 
> Btw your instance doesn't work on Edge 18 & older (the Edge before it was forked from Chromium) (TLS 1.2 & HTTP2 compatible), Internet Explorer 11 & older (TLS 1.2 & HTTP2 compatible), Google Chrome 70 & older (TLS 1.2 & HTTP2 compatible), Firefox 62 & older (TLS 1.3 & HTTP2 compatible), Safari desktop 11.1 & older (TLS 1.2 & HTTP2 compatible), Safari for IOS 11 & older version of IOS (TLS 1.2 & HTTP2 compatible), Google Chrome for IOS 11 & older version of IOS (TLS 1.2 & HTTP2 compatible) and Firefox for IOS 11 & older version of IOS (TLS 1.2 & HTTP2 compatible). Seems like a very long list of browsers that can't use your instance 😄.

thx! ~issue resolved

---

TLS 1.3 support list: https://caniuse.com/#search=tls%201.3
HTTP/2 support list: https://caniuse.com/#search=http%2F2

As I previously mentioned I am only focusing on supporting latest releases. There are so many searx instances available to choose from that if someone finds my instance unusable he or she is free to use a different one. I would rather provide a decent service to 90% of the people rather than average one to 99% of the people.
